# Site settings
title: 우주 - 서버 개발자
description: NBT 서버개발자
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yeonwoojoo.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yeon woojoo
user_description: 우주의 블로그
email: aziezle@naver.com
twitter_username: aziezle
github_username:  yeonwoojoo
gplus_username:  aziezle1001
disqus_username: disqus_SI09vJ7NIW

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
